package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import choreo.auto.AutoTrajectory;
import choreo.trajectory.SwerveSample;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.ProfiledPIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.SwerveModuleState;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.networktables.DoublePublisher;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructArrayPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* PID Control for turning in YAGSL */
    private final ProfiledPIDController thetaController;

    /* Publisher for observed swerve states */

    private final StructArrayPublisher m_observedPublisher = NetworkTableInstance.getDefault().g
            etStructArrayTopic("Swerve/Observed", SwerveModuleState.struct).publish();

    private final DoublePublisher m_thetaControllerPublisher = NetworkTableInstance.getDefault().g
            etDoubleTopic("Swerve/ThetaControllerOut").publish();

    private final DoublePublisher m_trajectoryHeadingPublisher = NetworkTableInstance.getDefault()
            .getDoubleTopic("Swerve/TrajectoryHeading").publish();pr*vate
    final DoublePublisher m_trajectoryOmegaPublisher = NetworkTableInstance
     * getDefault().getDoubl
     Topic("Swerve/TrajectoryOmega").publish();
    /* SysId routine for characterizing translation. This is used to find PI
            ate final SysIdRoutine m
                    SysId Config(
                    null,        // Use default ramp rate (1 V/s)
                    Volts // Reduce dynamic step voltag
                    null,        // Use default timeout 
                    // Log state with SignalLogger class  
            ),
                    SysIdRoutine.Mechanism(
                    outpu
                    null     )
    );

     * 
     * 
     
    /* SysId routine for characterizing steer. This is used to find PI
            ate final SysIdRoutine m
                    SysId Config(
                    null,        // Use default ramp rate (1 V
                    Volts // Use dynamic voltage of 7 V
                    null,        // Use default timeout 
                    // Log state with SignalLogger class  
            ),
                    SysIdRoutine.Mechanism(
                    volts
                    null     )
    );

    /*
     * SysId routine for characterizing rotation.
     * 
     * This is used to find PID gains for the FieldCentricFacingAngle Heading
     * ontroller.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
            ate final SysIdRoutine m
                    SysIdRoutine.Config(
                    /* This is in radians per second²,
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radi
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class  
            ),
                    SysIdRoutin
                        ut -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRot
                        /* also log the requested output for SysId */
                      
                    },null));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * 
     * This constructs the underlying hardware devices, so users should not c
     * nstruct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     * 
     * @param drivetr             Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
            ic CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConst    SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
                ezoidProfile
                2 * Math.PI,
            2 * Math.PI * Constants.SwerveConstants.kAngularAccelerationFactor);
                thetaController = new ProfiledPIDController(Constants.ChoreoConstants.kP_theta,
        Constants.ChoreoConstants.kI_theta, Constants.ChoreoConstants.kD_theta, yagslConstraints);
        thetaController.enableContinuousInput(-Math.PI, Math.PI);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * 
     * This constructs the underlying hardware devices, so users should not c
     * nstruct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
            ic CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drive
            double odometryUpdateFrequency,    SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
                ezoidProfile
                2 * Math.PI,
            2 * Math.PI * Constants.SwerveConstants.kAngularAccelerationFactor);
                thetaController = new ProfiledPIDController(Constants.ChoreoConstants.kP_theta,
        Constants.ChoreoConstants.kI_theta, Constants.ChoreoConstants.kD_theta, yagslConstraints);
        thetaController.enableContinuousInput(-Math.PI, Math.PI);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * 
     * This constructs the underlying hardware devices, so users should not c
     * nstruct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     *                                  
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     *                                  
     * @param odometryStandardDeviation The standard deviation for odometry calcu
     *                                  ation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     *                                  
     * @param visionStandardDeviation   The standard deviation for vision calcula
     *                                  ion
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
            ic CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drive
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviatio
            Matrix<N3, N1> visionStandardDeviation,    SwerveModuleConstants<?, ?, ?>... modules
    ) {
                
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, vi
                ezoidPr
                11.321,
            2 * 11.321 * Constants.SwerveConstants.kAngularAccelerationFactor);
                thetaController = new ProfiledPIDController(Constants.ChoreoConstants.kP_theta,
        Constants.ChoreoConstants.kI_theta, Constants.ChoreoConstants.kD_theta, yagslConstraints);
        thetaController.enableContinuousInput(-Math.PI, Math.PI);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * 
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRe

    quest(Supplier<SwerveRequest> r
            quest) {
        
        return run(() -> {this.setControl(request.get()); m_observedPublisher.set(this.getState().ModuleStates);});
    }

    public void followTrajectory(SwerveSample sample) {
        Pose2d pose = this.getPose();
        m_observedPublisher.set(this.getState().ModuleStates);
        m_thetaControllerPublisher.set(thetaController.calculate(pose.getRotation().getRadians(), sample.heading));
        m_trajectoryHeadingPublisher.set(sample.heading);
        m_trajectoryOmegaPublisher.set(sample.getTimesta
                veRequest.FieldCentric()
                .withVelocityX(sample.vx + Constants.ChoreoConstants.xController.calculate(pose.getX(), sample.x))
                .withVelocityY(sampl
                        e.vy + Constants.ChoreoConstants.yController.calculate(pose.getY(), sample.y))
                                .withRotationalRate(sample.omega + thetaController.calculate(pose.getRotation().getRadians(), sample.heading)));
    }

    public Command goToEndPose(AutoTrajectory traj) {
        Command output = Commands.none();
        try {
            output = Commands.run(() -> {
                Pose2d pose = this.getPose();
                Pose2d end = traj.getFinalPose().get();
                this.setControl(new SwerveRequest.FieldCentric()
                        .withVelocityX(Constants.ChoreoConstants.xController.calculate(pose.getX(), end.getX()))
                        .withVelocityY(Constants.ChoreoConstants.yController.calculate(pose.getY(), end.getY()))
                        .withRotationalRate(thetaController.calculate(pose.getRotation().getRadians(),
                                end.getRotation().getRadians())));
            });
        } catch (Exception e) {

        

    
    public Command stopRobot() {

        return Commands.run(() -> {
            this.setControl(new SwerveRequest.FieldCentric().withVelocityX(0).withVelocityY(0).withRotationalRate(0));
        });
    }

    public Pose2d getPose() {
        return this.samplePoseAt(Utils.getCurrentTimeSeconds()).orElse(new Pose2d());
    }

    public void resetThetaController() {

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * 
         * If we haven't applied the operator perspective before, then we should app
         * y it regardless of DS state.
         * This allows us to correct the perspective in case the robot code rest
         * rts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabl
         * d.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPres
                        peratorPerspectiveForward(
                                anceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * 
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * 
     * @param visionRobotPoseM ters The pose of the robot as measured by
     *                         he vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * 
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     * 
     * 
     * @param visionRobotPoseM ters The pose of the robot as measured by
     *                         he vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in sec
     *                         nds.
     *                         am visionMeasurementStdDevs Standard devi
     *                         tions of the vision pose measurement
     *                         in the form [x, y, theta]ᵀ, with units in meters and
     *                         radians.
     */
    @Override
            ic void addVisionMeasurement(
            Pose2d visionRobotPoseMe
            double timestampSeconds,    Matrix<N3, N1> visionMeasurementStdDevs
    ) {
                
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * 
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}
